// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMpYRRsXBJlDr-BVgtly4X3LkY5WPu94',
    appId: '1:909466769672:web:55a3a124ecc9448f52b4bd',
    messagingSenderId: '909466769672',
    projectId: 'skillswap-3f989',
    authDomain: 'skillswap-3f989.firebaseapp.com',
    storageBucket: 'skillswap-3f989.firebasestorage.app',
    measurementId: 'G-92XGB0J3G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0UU4Q9qcSH8WmvEOKYb63hklD9m0_S8',
    appId: '1:909466769672:android:37ff96ed6c5391ae52b4bd',
    messagingSenderId: '909466769672',
    projectId: 'skillswap-3f989',
    storageBucket: 'skillswap-3f989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy0H-uYiw0YDo-2zkJyRgZQ88ctWkyvB0',
    appId: '1:909466769672:ios:01ec3ce354cf49f552b4bd',
    messagingSenderId: '909466769672',
    projectId: 'skillswap-3f989',
    storageBucket: 'skillswap-3f989.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy0H-uYiw0YDo-2zkJyRgZQ88ctWkyvB0',
    appId: '1:909466769672:ios:01ec3ce354cf49f552b4bd',
    messagingSenderId: '909466769672',
    projectId: 'skillswap-3f989',
    storageBucket: 'skillswap-3f989.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMpYRRsXBJlDr-BVgtly4X3LkY5WPu94',
    appId: '1:909466769672:web:c8832a11095adac452b4bd',
    messagingSenderId: '909466769672',
    projectId: 'skillswap-3f989',
    authDomain: 'skillswap-3f989.firebaseapp.com',
    storageBucket: 'skillswap-3f989.firebasestorage.app',
    measurementId: 'G-NPF0L8ES0C',
  );
}
